### ISSUE TITLE
Error while installing with Node 10 on Windows

### ISSUE THREAD

**Issue by ThomasdenH** [robertklep/node-metrohash#5]
I get the following output while running `npm install metrohash` on Windows with Node.js 10.0.0:

```
if not defined npm_config_node_gyp (node "C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  metrohash_wrapper.cpp
  metrohash128.cpp
  metrohash128crc.cpp
  metrohash64.cpp
  win_delay_load_hook.cc
..\src\metrohash_wrapper.cpp(24): warning C4244: 'argument': conversion from 'double' to 'uint64_t', possible loss of data [D:\Documenten\a\node_modules\metrohash\build\metrohash.vcxproj]
  ..\src\metrohash_wrapper.cpp(20): note: while compiling class template member function 'Nan::NAN_METHOD_RETURN_TYPE NodeMetroHash<MetroHash128,16>::New(Nan::NAN_METHOD_ARGS_TYPE)'
  ..\src\metrohash_wrapper.cpp(85): note: see reference to function template instantiation 'Nan::NAN_METHOD_RETURN_TYPE NodeMetroHash<MetroHash128,16>::New(Nan::NAN_METHOD_ARGS_TYPE)' being compiled
  ..\src\metrohash_wrapper.cpp(147): note: see reference to class template instantiation 'NodeMetroHash<MetroHash128,16>' being compiled
..\src\metrohash_wrapper.cpp(31): error C2661: 'v8::Function::NewInstance': no overloaded function takes 2 arguments [D:\Documenten\a\node_modules\metrohash\build\metrohash.vcxproj]
```

The command does work with Node 8.11.1.

**Comment by robertklep** [comment]
TBH, I haven't looked at support for Node 10 yet. It might be as simple as updating `nan` to a later version, but I'd have to check.

**Comment by ThomasdenH** [comment]
That's a quick response! Personally I am not in a hurry to upgrade to Node 10, I just thought I might notify you.

**Comment by robertklep** [comment]
Thanks :) Looks like I already fixed it, will push a new version soon.

**Comment by ThomasdenH** [comment]
Super, thanks!

**Comment by robertklep** [comment]
Just published v2.4.0 which should work on Node 10 👍
